name: 'Install and Cache Node Modules'
description: 'Description about Cache Node Modules'
inputs:
  caching:
    required: false
    # required: true
    description: "Enable or disable caching"
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      if: inputs.caching == 'true'
      id: cache-step
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cache-file-
          ${{ runner.os }}-
    - name: Display Cache
      run: echo '${{ toJSON(steps.cache-step.outputs) }}'
      shell: bash
    - name: Install node_modules
      run: npm install
      shell: bash