name: Concurrency Testing
on: workflow_dispatch
concurrency: concurrency-testing

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Some Step
        run: sleep 50
        timeout-minutes: 1