name: Docker Test
on: push

jobs:
  test-docker-container:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine3.19
      # image: node:12
      env:
        NODE_ENV: development
      ports:
        - 80
      # volumes:
      #   - docker_volumes:/volumes
      # options: --cpus 1
    steps:
      - name: Display Node Version
        run: |
          node -v
          cat /etc/os-release
      - name: Print new Node Version
        uses: docker://node:18-bullseye-slim
        with:
          args: -v