name: First WorkFlow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Text
        run: echo "Some Text"
      - name: Display in Multiline
        run: |
          node -v
          npm -v