name: Fourteenth WorkFlow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_molules
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.nmp
          key: "cache-file"
      - name: Display Cache
        run: echo '${{ steps.cache-step.outputs }}'
      - name: Install node_molules
        run: npm install