name: Fourth WorkFlow
on: 
  workflow_run:
    workflows: [Third WorkFlow]
    types:
      - completed

jobs:
  run-action-complete:
    runs-on: ubuntu-latest
    steps:
      - name: List Files and Copy Repository
        run: echo "Action Complete"