name: Seventeenth WorkFlow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false

jobs:
  call-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}
  call-external-workflow:
    uses: SSgtd77/workflows/.github/workflows/workflow.yml@main
    secrets: 
      PASSWORD: ${{ secrets.PASSWORD_MAIN }}
  display-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo ${{ needs.call-workflow.outputs.date }}