name: Thirteenth WorkFlow
on: push
run-name: "Failure with conditions"

jobs:
  # failure() success() always() cancelled()
  job-first:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Step
        id: error-step
        run: exit 1
      - name: Runs on Canceled
        if: ${{ cancelled() }}
        run: echo "Runs on Canceled"
      - name: Runs on any case
        if: ${{ always() }}
        run: echo "Runs on any case"
      - name: Runs on Success
        if: ${{ success() }}
        run: echo "Runs on Success"
      - name: Runs on Failure
        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
        run: echo "Runs on Failure"
  job-second:
    runs-on: ubuntu-latest
    needs: job-first
    if: ${{ failure() }}
    steps:
      - name: Second Job
        run: echo "Job was failed"