name: Twelfth WorkFlow
on: [push]
run-name: "Environment Production Variables"

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Our Vars and Secrects
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'