name: Twelfth WorkFlow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Our Vars and Secrects
        env:
          STEP_CUSTOM_VAR: STEP 1
          WF_CUSTOM_VAR: WF 1 - STEP 2
        run: |
          echo '${{ vars.STATUS_MAIN }}'
          echo '${{ secrets.PASSWORD_MAIN }}'