name: Twelfth WorkFlow
on: [push]
run-name: "Environment Staging Variables"

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Our Vars and Secrects
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'